CREATE TABLE airlines (
"airport_code" varchar(50),
"airport_name" varchar(max),
"time_label" varchar(50),
"time_month" bigint,
"time_month_name" varchar(50),
"time_year" bigint,
"statistics_numb_of_delays_carrier" bigint,
"statistics_numb_of_delays_late_aircraft" bigint,
"statistics_numb_of_delays_national_aviation_system" bigint,
"statistics_numb_of_delays_security" bigint,
"statistics_numb_of_delays_weather" bigint,
"statistics_carriers_names" varchar(max),
"statistics_carriers_total" bigint,
"statistics_flights_cancelled" bigint,
"statistics_flights_delayed" bigint,
"statistics_flights_diverted" bigint,
"statistics_flights_on_time" bigint,
"statistics_flights_total" bigint,
"statistics_minutes_delayed_carrier" bigint,
"statistics_minutes_delayed_late_aircraft" bigint,
"statistics_minutes_delayed_national_aviation_system" bigint,
"statistics_minutes_delayed_security" bigint,
"statistics_minutes_delayed_total" bigint,
"statistics_minutes_delayed_weather" bigint
)

